# Generated by Django 5.1.4

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(Warehouse, source: str) -> str:
    base = slugify(source).lower() or "warehouse"
    slug = base
    counter = 2
    while Warehouse.objects.filter(slug=slug).exists():
        slug = f"{base}-{counter}"
        counter += 1
    return slug


def assign_default_warehouses(apps, schema_editor):
    """Give existing items a warehouse so the FK can become required."""
    Organization = apps.get_model("organizations", "Organization")
    Warehouse = apps.get_model("inventory", "Warehouse")
    Item = apps.get_model("inventory", "Item")
    for org in Organization.objects.all():
        if not Item.objects.filter(org=org).exists():
            continue
        warehouse = Warehouse.objects.filter(org=org).first()
        if warehouse is None:
            warehouse = Warehouse.objects.create(
                org=org,
                name="Warehouse",
                slug=_unique_slug(Warehouse, "Warehouse"),
            )
        Item.objects.filter(org=org, warehouse__isnull=True).update(
            warehouse=warehouse
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("organizations", "0002_space"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, db_index=True, max_length=255, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("org", "name"),
                name="inventory_warehouse_org_name_uniq",
            ),
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, db_index=True, max_length=255, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_categories",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item category",
                "verbose_name_plural": "Item categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                fields=("org", "name"),
                name="inventory_itemcategory_org_name_uniq",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="inventory_item_org_name_uniq",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="sku",
            new_name="part_number",
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="alternate_part_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="last_purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="last_purchase_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.itemcategory",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.warehouse",
            ),
        ),
        migrations.RunPython(assign_default_warehouses, noop_reverse),
        migrations.AlterField(
            model_name="item",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "name"),
                name="inventory_item_warehouse_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("part_number", ""), _negated=True),
                fields=("warehouse", "part_number"),
                name="inventory_item_warehouse_part_uniq",
            ),
        ),
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, db_index=True, max_length=255, unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="items/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item photo",
                "verbose_name_plural": "Item photos",
                "ordering": ["created_at"],
            },
        ),
    ]
