# Generated by Django 5.1.4 on 2026-09-22 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_catalog_fields'),
        ('organizations', '0003_alter_organization_is_active_and_more'),
        ('users', '0006_operation_space_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('actor_slug', models.SlugField(blank=True, max_length=255)),
                ('actor_full_name', models.CharField(blank=True, max_length=301)),
                ('actor_user_type', models.CharField(blank=True, max_length=32)),
                ('kind', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('item_edit', 'Item edit')], max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('added', 'Added'), ('removed', 'Removed'), ('received', 'Received'), ('suspended', 'Suspended'), ('unsuspended', 'Unsuspended'), ('photo_added', 'Photo added'), ('photo_deleted', 'Photo deleted')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('previous_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reference_type', models.CharField(default='item_activity', max_length=64)),
                ('reference_slug', models.SlugField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_activities', to='users.userprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inventory.item')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_activities', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Item activity',
                'verbose_name_plural': 'Item activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
