# Generated by Django 5.1.4 on 2026-09-16 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive vendors are hidden from purchasing flows.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('org', 'name'), name='vendors_vendor_org_name_uniq')],
            },
        ),
    ]
