# Generated by Django 5.1.4 on 2026-09-17 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0003_alter_organization_is_active_and_more'),
        ('users', '0006_operation_space_incharge'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('qc_pending', 'QC pending'), ('qc_failed', 'QC failed'), ('received', 'Received'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='issued', max_length=32)),
                ('is_new_order', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='organizations.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Purchase order',
                'verbose_name_plural': 'Purchase orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('document_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment')], default='pending_payment', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase invoice',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revision_requested', 'Revision requested'), ('declined', 'Declined')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='users.userprofile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_requests', to='users.userprofile')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='organizations.space')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchases.purchaserequest'),
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_slug', models.SlugField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('actor_slug', models.SlugField(max_length=255)),
                ('actor_user_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('signature', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_events', to='organizations.organization')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_events', to='purchases.purchaserequest')),
            ],
            options={
                'verbose_name': 'Process event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('awarded_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_request_lines', to='vendors.vendor')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase request line',
                'verbose_name_plural': 'Purchase request lines',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder')),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='purchases.purchaserequestline')),
            ],
            options={
                'verbose_name': 'Purchase order line',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('passed', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=32)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='users.userprofile')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Quality check',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('in_review', 'In review'), ('awarding', 'Awarding'), ('cancelled', 'Cancelled')], default='preparing', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='organizations.organization')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='purchases.purchaserequest')),
            ],
            options={
                'verbose_name': 'Quote request',
                'verbose_name_plural': 'Quote requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('quoted', 'Quoted'), ('rejected', 'Rejected'), ('awarded', 'Awarded')], default='invited', max_length=32)),
                ('reject_reason', models.TextField(blank=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='purchases.quoterequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_request_vendors', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'RFQ vendor',
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('quoted_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request_vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='purchases.quoterequestvendor')),
            ],
            options={
                'verbose_name': 'Vendor quote',
            },
        ),
        migrations.CreateModel(
            name='VendorQuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.vendorquote')),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchases.purchaserequestline')),
            ],
            options={
                'verbose_name': 'Vendor quote line',
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipts', to='organizations.organization')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipt', to='purchases.purchaseorder')),
            ],
            options={
                'verbose_name': 'Warehouse receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='inventory.item')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchases.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.warehousereceipt')),
            ],
            options={
                'verbose_name': 'Warehouse receipt line',
            },
        ),
        migrations.AddConstraint(
            model_name='quoterequestvendor',
            constraint=models.UniqueConstraint(fields=('quote_request', 'vendor'), name='purchases_rfq_vendor_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendorquoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'request_line'), name='purchases_quote_line_uniq'),
        ),
    ]
