# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_item_catalog_fields"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousereceipt",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="inventory.warehouse",
            ),
        ),
    ]
