# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_warehousereceipt_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
