# Generated by Django 5.1.4 on 2026-09-17 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive organisations cannot log in.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_suffix',
            field=models.CharField(help_text='Unique handle for this organisation (lowercase letters, digits, underscores).', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='org_suffix may only contain lowercase letters, digits, and underscores.', regex='^[a-z0-9_]+$')]),
        ),
    ]
